FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5021

ENV ASPNETCORE_URLS=http://+:5021

USER app
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG configuration=Release
WORKDIR /src
COPY ["AspnetObservability.API/AspnetObservability.API.csproj", "AspnetObservability.API/"]
RUN dotnet restore "AspnetObservability.API/AspnetObservability.API.csproj"
COPY . .
WORKDIR "/src/AspnetObservability.API"
RUN dotnet build "AspnetObservability.API.csproj" -c $configuration -o /app/build

FROM build AS publish
ARG configuration=Release
RUN dotnet publish "AspnetObservability.API.csproj" -c $configuration -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AspnetObservability.API.dll"]
